import { AnalyzedReport, ReportSummary } from '@lynsight/core';
import { EnrichedNarratives, EnrichedReport } from '@lynsight/llm';
import { GRADE_COLORS, SEVERITY_COLORS } from './colors.js';

export interface HtmlReportInput {
  analyzed: AnalyzedReport;
  enriched?: EnrichedReport;
  /** Optional title override; defaults to hostname or "Lynis audit". */
  title?: string;
  /** Generation timestamp; defaults to now(). */
  generatedAt?: Date;
  /**
   * If true, the page is laid out for print (margins, no dark background,
   * page-break hints). Used by the PDF renderer.
   */
  printMode?: boolean;
}

/**
 * Renders a fully self-contained HTML report (no external CSS/JS, no fonts,
 * no remote assets). Charts are inline SVG so the same artifact can be opened
 * offline, attached to a ticket, or printed/exported to PDF via Playwright.
 */
export function renderHtml(input: HtmlReportInput): string {
  const { analyzed, enriched } = input;
  const { report, summary } = analyzed;
  const generatedAt = input.generatedAt ?? new Date();
  const title = input.title ?? `Lynsight report - ${report.system.hostname ?? 'Lynis audit'}`;
  const printMode = input.printMode ?? false;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<style>${printMode ? CSS_PRINT : CSS}</style>
</head>
<body class="${printMode ? 'print' : ''}">
<header>
  <div class="brand">Lynsight <span class="muted">v0.1</span></div>
  <div class="muted">${esc(generatedAt.toISOString())}</div>
</header>

<h1>${esc(title)}</h1>

<section class="cards">
  ${gradeCard(summary.grade)}
  ${scoreCard('Risk score', summary.riskScore, '/100', riskHint(summary.riskScore))}
  ${scoreCard('Hardening index', summary.hardeningIndex ?? '—', summary.hardeningIndex !== null ? '/100' : '', 'Lynis built-in')}
  ${countCard('Findings', report.findings.length)}
  ${strengthsCard(summary.strengths.length, summary.strengthsPointsAwarded, summary.strengthsPointsMax)}
</section>

${narrativeBlock('Executive summary', enriched?.narratives.executiveSummary)}

<section>
  <h2>Severity breakdown</h2>
  ${severityBars(summary.totals)}
</section>

<section>
  <h2>By category</h2>
  <table>
    <thead><tr><th>Category</th><th>Total</th><th>Critical</th><th>High</th><th>Medium</th><th>Low</th></tr></thead>
    <tbody>
      ${summary.byCategory
        .map(
          (b) => `<tr>
            <td><span class="dot" style="background:${b.color}"></span> ${esc(b.label)}</td>
            <td>${b.total}</td>
            <td>${b.bySeverity.critical}</td>
            <td>${b.bySeverity.high}</td>
            <td>${b.bySeverity.medium}</td>
            <td>${b.bySeverity.low}</td>
          </tr>`,
        )
        .join('')}
    </tbody>
  </table>
</section>

${narrativeBlock('Risk narrative', enriched?.narratives.riskNarrative)}
${narrativeBlock('Attack surface', enriched?.narratives.attackSurface)}
${narrativeBlock('Action roadmap', enriched?.narratives.actionRoadmap)}
${narrativeBlock('Compliance posture', enriched?.narratives.compliance)}

${strengthsSection(summary)}

<section class="page-break">
  <h2>Top findings</h2>
  ${summary.topFindings
    .map((f) => {
      const enrichedNote = enriched?.findings.find((x) => x.id === f.id)?.llmRemediation;
      return `<article class="finding sev-${f.severity}">
        <header>
          <span class="badge" style="background:${SEVERITY_COLORS[f.severity]}">${f.severity.toUpperCase()}</span>
          <strong>${esc(f.id)}</strong>
          <span class="muted">${esc(f.category)}</span>
        </header>
        <p>${esc(f.description)}</p>
        ${f.details ? `<details ${printMode ? 'open' : ''}><summary>Details</summary><pre>${esc(f.details)}</pre></details>` : ''}
        ${f.solution ? `<details ${printMode ? 'open' : ''}><summary>Lynis hint</summary><pre>${esc(f.solution)}</pre></details>` : ''}
        ${enrichedNote ? `<details open><summary>AI remediation</summary><div class="md">${mdLite(enrichedNote)}</div></details>` : ''}
      </article>`;
    })
    .join('')}
</section>

<section>
  <h2>System</h2>
  <table class="kv">
    ${kv('Hostname', report.system.hostname)}
    ${kv('OS', report.system.osFullName ?? report.system.os)}
    ${kv('Kernel', report.system.kernelVersion)}
    ${kv('Lynis version', report.meta.lynisVersion)}
    ${kv('Tests executed', report.meta.testsExecuted)}
    ${kv('Tests skipped', report.meta.testsSkipped)}
    ${kv('Auditor', report.meta.auditorName)}
    ${kv('Started', report.meta.reportDatetimeStart)}
    ${kv('Ended', report.meta.reportDatetimeEnd)}
  </table>
</section>

<footer class="muted">Generated by Lynsight - open-source Lynis reporter. ${enriched ? `LLM: ${esc(enriched.meta.providerName)} · ${enriched.meta.enrichedCount} findings + ${narrativesCount(enriched.narratives)} narratives.` : 'Run with --llm to enrich findings.'}</footer>
</body>
</html>`;
}

function narrativesCount(n: EnrichedNarratives): number {
  return Object.values(n).filter(Boolean).length;
}

function narrativeBlock(title: string, content: string | undefined): string {
  if (!content) return '';
  return `<section class="narrative"><h2>${esc(title)}</h2><div class="md">${mdLite(content)}</div></section>`;
}

function gradeCard(grade: 'A' | 'B' | 'C' | 'D' | 'F'): string {
  return `<div class="card grade" style="--c:${GRADE_COLORS[grade]}">
    <div class="label">Overall grade</div>
    <div class="grade-letter">${grade}</div>
  </div>`;
}

function scoreCard(label: string, value: number | string, suffix: string, hint: string): string {
  return `<div class="card">
    <div class="label">${esc(label)}</div>
    <div class="value">${value}<span class="suffix">${esc(suffix)}</span></div>
    <div class="muted">${esc(hint)}</div>
  </div>`;
}

function countCard(label: string, value: number): string {
  return `<div class="card">
    <div class="label">${esc(label)}</div>
    <div class="value">${value}</div>
  </div>`;
}

function strengthsCard(count: number, awarded: number, max: number): string {
  const ratio = max > 0 ? Math.round((awarded / max) * 100) : 0;
  const hint = max > 0 ? `${awarded} / ${max} pts (${ratio}%)` : 'Hardening controls in place';
  return `<div class="card strengths-card">
    <div class="label">✓ Strengths</div>
    <div class="value">${count}</div>
    <div class="muted">${esc(hint)}</div>
  </div>`;
}

function strengthsSection(summary: ReportSummary): string {
  if (!summary.strengths.length) return '';
  // Per-category breakdown table.
  const rows = summary.strengthsByCategory
    .map(
      (b) => `<tr>
        <td><span class="dot" style="background:${b.color}"></span> ${esc(b.label)}</td>
        <td>${b.count}</td>
        <td>${b.pointsAwarded}${b.pointsMax ? ` / ${b.pointsMax}` : ''}</td>
        <td class="muted ids">${b.testIds.slice(0, 6).map(esc).join(', ')}${b.testIds.length > 6 ? ` …+${b.testIds.length - 6}` : ''}</td>
      </tr>`,
    )
    .join('');
  // Full list, collapsed by default to avoid drowning the report.
  const items = summary.strengths
    .map(
      (s) =>
        `<li><code>${esc(s.id)}</code> · <span class="muted">${esc(s.category)}</span> · ${s.pointsAwarded}${s.pointsMax ? ` / ${s.pointsMax}` : ''} pts${s.description ? ` - ${esc(s.description)}` : ''}</li>`,
    )
    .join('');
  return `<section class="strengths">
    <h2>Strengths - hardening controls in place</h2>
    <p class="muted">These Lynis tests passed: the corresponding hardening control is active on the host. Use this list to confirm that previous remediation work is still effective.</p>
    <table>
      <thead><tr><th>Category</th><th>Tests</th><th>Points</th><th>Test IDs</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <details>
      <summary>Show all ${summary.strengths.length} passing tests</summary>
      <ul class="strengths-list">${items}</ul>
    </details>
  </section>`;
}

function riskHint(s: number): string {
  if (s < 10) return 'Excellent posture';
  if (s < 25) return 'Good';
  if (s < 50) return 'Needs attention';
  if (s < 75) return 'Poor';
  return 'Critical';
}

function severityBars(totals: Record<string, number>): string {
  const order: Array<keyof typeof SEVERITY_COLORS> = ['critical', 'high', 'medium', 'low', 'info'];
  const max = Math.max(1, ...order.map((k) => totals[k] ?? 0));
  return `<div class="bars">
    ${order
      .map((k) => {
        const v = totals[k] ?? 0;
        const w = (v / max) * 100;
        return `<div class="bar-row">
          <span class="bar-label">${k}</span>
          <div class="bar-track"><div class="bar-fill" style="width:${w}%;background:${SEVERITY_COLORS[k]}"></div></div>
          <span class="bar-value">${v}</span>
        </div>`;
      })
      .join('')}
  </div>`;
}

function kv(k: string, v: unknown): string {
  return `<tr><th>${esc(k)}</th><td>${esc(v == null ? '—' : String(v))}</td></tr>`;
}

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Tiny Markdown-ish renderer (headings, bold, inline code, fenced code,
 * lists, tables, links). We avoid pulling in a full markdown lib to keep
 * the report self-contained and dep-free.
 */
function mdLite(input: string): string {
  const lines = input.split(/\r?\n/);
  const out: string[] = [];
  let inCode = false;
  let inList = false;
  let table: string[] | null = null;

  const flushTable = () => {
    if (!table) return;
    const rows = table.map((row) => row.trim()).filter((r) => r.startsWith('|'));
    const parsed = rows.map((r) =>
      r
        .replace(/^\||\|$/g, '')
        .split('|')
        .map((c) => c.trim()),
    );
    if (parsed.length >= 2) {
      const header = parsed[0]!;
      const body = parsed.slice(2); // skip separator row
      out.push('<table>');
      out.push(
        '<thead><tr>' + header.map((h) => `<th>${inline(h)}</th>`).join('') + '</tr></thead>',
      );
      out.push('<tbody>');
      for (const r of body) {
        out.push('<tr>' + r.map((c) => `<td>${inline(c)}</td>`).join('') + '</tr>');
      }
      out.push('</tbody></table>');
    }
    table = null;
  };

  for (const raw of lines) {
    if (raw.startsWith('```')) {
      flushTable();
      if (inCode) {
        out.push('</pre>');
        inCode = false;
      } else {
        out.push('<pre>');
        inCode = true;
      }
      continue;
    }
    if (inCode) {
      out.push(esc(raw));
      continue;
    }
    if (/^\s*\|.*\|\s*$/.test(raw)) {
      table ??= [];
      table.push(raw);
      continue;
    } else if (table) {
      flushTable();
    }
    if (/^\s*[-*]\s+/.test(raw)) {
      if (!inList) {
        out.push('<ul>');
        inList = true;
      }
      out.push(`<li>${inline(raw.replace(/^\s*[-*]\s+/, ''))}</li>`);
      continue;
    }
    if (inList) {
      out.push('</ul>');
      inList = false;
    }
    const h = /^(#{1,6})\s+(.+)$/.exec(raw);
    if (h) {
      const lvl = h[1]!.length;
      out.push(`<h${lvl + 2}>${inline(h[2]!)}</h${lvl + 2}>`);
      continue;
    }
    if (raw.trim() === '') out.push('');
    else out.push(`<p>${inline(raw)}</p>`);
  }
  if (inList) out.push('</ul>');
  if (inCode) out.push('</pre>');
  flushTable();
  return out.join('\n');
}

function inline(s: string): string {
  return esc(s)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');
}

const CSS = `
:root {
  --bg: #0b1020;
  --panel: #131a2e;
  --text: #e6e9f2;
  --muted: #8a93a6;
  --border: #1f2740;
  --accent: #6366f1;
}
@media (prefers-color-scheme: light) {
  :root { --bg:#f7f8fb; --panel:#fff; --text:#0b1020; --muted:#5b6477; --border:#e3e6ee; }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 32px; max-width: 1100px; margin-inline:auto;
  background: var(--bg); color: var(--text);
  font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
}
header { display:flex; justify-content:space-between; align-items:center; margin-bottom: 8px; }
.brand { font-weight:700; letter-spacing:.5px; }
.muted { color: var(--muted); font-size: 12px; }
h1 { margin: 0 0 24px; font-size: 28px; }
h2 { margin: 32px 0 12px; font-size: 18px; border-bottom: 1px solid var(--border); padding-bottom: 6px; }
section { margin-bottom: 24px; }
.cards { display:grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.card { background: var(--panel); border:1px solid var(--border); border-radius: 12px; padding: 16px; }
.card .label { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
.card .value { font-size: 28px; font-weight: 700; margin-top: 4px; }
.card .suffix { font-size: 14px; color: var(--muted); margin-left: 4px; font-weight: 500; }
.card.grade { text-align:center; border-color: var(--c); }
.card.grade .grade-letter { font-size: 48px; font-weight: 800; color: var(--c); line-height: 1; }
table { width: 100%; border-collapse: collapse; background: var(--panel); border:1px solid var(--border); border-radius: 12px; overflow: hidden; }
th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid var(--border); }
th { background: rgba(255,255,255,.02); font-size: 12px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); }
tr:last-child td { border-bottom: none; }
.kv th { width: 200px; }
.dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 6px; vertical-align: middle; }
.bars { display:flex; flex-direction: column; gap: 6px; background: var(--panel); border:1px solid var(--border); border-radius: 12px; padding: 16px; }
.bar-row { display: grid; grid-template-columns: 100px 1fr 60px; gap: 12px; align-items: center; }
.bar-label { text-transform: capitalize; color: var(--muted); font-size: 12px; }
.bar-value { text-align: right; font-variant-numeric: tabular-nums; }
.bar-track { height: 10px; background: rgba(255,255,255,.05); border-radius: 999px; overflow: hidden; }
.bar-fill { height: 100%; border-radius: 999px; }
.finding { background: var(--panel); border: 1px solid var(--border); border-left-width: 4px; border-radius: 10px; padding: 14px 16px; margin-bottom: 10px; }
.finding.sev-critical { border-left-color: ${SEVERITY_COLORS.critical}; }
.finding.sev-high { border-left-color: ${SEVERITY_COLORS.high}; }
.finding.sev-medium { border-left-color: ${SEVERITY_COLORS.medium}; }
.finding.sev-low { border-left-color: ${SEVERITY_COLORS.low}; }
.finding header { gap: 8px; align-items: center; }
.badge { display: inline-block; color: white; font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 999px; letter-spacing: .5px; margin-right: 6px; }
.finding p { margin: 8px 0; }
.finding details { margin-top: 6px; }
.finding pre { background: rgba(0,0,0,.25); border-radius: 8px; padding: 10px; overflow:auto; font-size: 12px; }
@media (prefers-color-scheme: light) { .finding pre { background: #f1f3f9; } }
.narrative .md { background: var(--panel); border:1px solid var(--border); border-radius: 12px; padding: 16px; }
.md p { margin: 4px 0 8px; }
.md code { background: rgba(127,127,127,.15); padding: 1px 4px; border-radius: 4px; font-size: 12px; }
.md pre { background: rgba(0,0,0,.2); padding: 10px; border-radius: 8px; overflow:auto; }
.md ul { margin: 4px 0 8px 18px; padding: 0; }
.md table { margin: 8px 0; }
footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border); }
.cards { grid-template-columns: repeat(5, 1fr); }
.strengths-card { border-color: #22c55e; }
.strengths-card .label { color: #22c55e; }
.strengths .ids { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; }
.strengths-list { margin: 8px 0 0 18px; padding: 0; columns: 2; column-gap: 24px; font-size: 12px; }
.strengths-list li { break-inside: avoid; margin-bottom: 4px; }
.strengths details summary { cursor: pointer; margin-top: 8px; color: var(--muted); font-size: 12px; }
@media (max-width: 720px) { .cards { grid-template-columns: repeat(2, 1fr); } .bar-row { grid-template-columns: 80px 1fr 50px; } .strengths-list { columns: 1; } }
@media print { body { background: white; color: black; } .card, table, .bars, .finding, .narrative .md { background: white; border-color: #ccc; } .page-break { page-break-before: always; } }
`;

const CSS_PRINT =
  CSS +
  `
body { background: white !important; color: #0b1020 !important; padding: 24px; max-width: 100%; }
.card, table, .bars, .finding, .narrative .md { background: white !important; border-color: #d4d8e0 !important; }
.muted { color: #5b6477 !important; }
h2 { border-bottom-color: #d4d8e0 !important; }
.finding pre, .md pre { background: #f4f5fa !important; color: #0b1020 !important; }
.bar-track { background: #eef0f5 !important; }
section { page-break-inside: avoid; }
.finding { page-break-inside: avoid; }
.page-break { page-break-before: always; }
`;
