import { AnalyzedReport } from '@lynsight/core';
import { EnrichedReport } from '@lynsight/llm';

export function renderMarkdown(analyzed: AnalyzedReport, enriched?: EnrichedReport): string {
  const { report, summary } = analyzed;
  const out: string[] = [];

  out.push(`# Lynsight report — ${report.system.hostname ?? 'Lynis audit'}`);
  out.push('');
  out.push(`> Generated ${new Date().toISOString()}`);
  out.push('');
  out.push('## Summary');
  out.push('');
  out.push(`| Metric | Value |`);
  out.push(`| --- | --- |`);
  out.push(`| Grade | **${summary.grade}** |`);
  out.push(`| Risk score | ${summary.riskScore} / 100 |`);
  out.push(`| Hardening index | ${summary.hardeningIndex ?? '—'} / 100 |`);
  out.push(`| Findings (total) | ${report.findings.length} |`);
  out.push(`| Critical | ${summary.totals.critical} |`);
  out.push(`| High | ${summary.totals.high} |`);
  out.push(`| Medium | ${summary.totals.medium} |`);
  out.push(`| Low | ${summary.totals.low} |`);
  out.push(
    `| Strengths (controls in place) | ${summary.strengths.length}${summary.strengthsPointsMax ? ` (${summary.strengthsPointsAwarded} / ${summary.strengthsPointsMax} pts)` : ''} |`,
  );
  out.push('');

  pushNarrative(out, 'Executive summary', enriched?.narratives.executiveSummary);
  pushNarrative(out, 'Risk narrative', enriched?.narratives.riskNarrative);
  pushNarrative(out, 'Attack surface', enriched?.narratives.attackSurface);
  pushNarrative(out, 'Action roadmap', enriched?.narratives.actionRoadmap);
  pushNarrative(out, 'Compliance posture', enriched?.narratives.compliance);

  out.push('## By category');
  out.push('');
  out.push('| Category | Total | Critical | High | Medium | Low |');
  out.push('| --- | ---: | ---: | ---: | ---: | ---: |');
  for (const b of summary.byCategory) {
    out.push(
      `| ${b.label} | ${b.total} | ${b.bySeverity.critical} | ${b.bySeverity.high} | ${b.bySeverity.medium} | ${b.bySeverity.low} |`,
    );
  }
  out.push('');

  if (summary.strengths.length) {
    out.push('## Strengths — hardening controls in place');
    out.push('');
    out.push(
      `${summary.strengths.length} Lynis tests passed (${summary.strengthsPointsAwarded}${summary.strengthsPointsMax ? ` / ${summary.strengthsPointsMax}` : ''} hardening points). These confirm previous remediation work is still effective.`,
    );
    out.push('');
    out.push('| Category | Tests | Points | Test IDs |');
    out.push('| --- | ---: | ---: | --- |');
    for (const b of summary.strengthsByCategory) {
      const ids =
        b.testIds.slice(0, 6).join(', ') +
        (b.testIds.length > 6 ? ` …+${b.testIds.length - 6}` : '');
      out.push(
        `| ${b.label} | ${b.count} | ${b.pointsAwarded}${b.pointsMax ? ` / ${b.pointsMax}` : ''} | ${ids} |`,
      );
    }
    out.push('');
  }

  out.push('## Top findings');
  out.push('');
  for (const f of summary.topFindings) {
    out.push(`### [${f.severity.toUpperCase()}] ${f.id} — ${f.description}`);
    out.push('');
    if (f.details) {
      out.push('**Details:**');
      out.push('');
      out.push('```');
      out.push(f.details);
      out.push('```');
      out.push('');
    }
    if (f.solution) {
      out.push(`**Lynis hint:** ${f.solution}`);
      out.push('');
    }
    const llm = enriched?.findings.find((x) => x.id === f.id)?.llmRemediation;
    if (llm) {
      out.push('**AI remediation:**');
      out.push('');
      out.push(llm.trim());
      out.push('');
    }
  }

  out.push('## System');
  out.push('');
  out.push(`- Hostname: ${report.system.hostname ?? '—'}`);
  out.push(`- OS: ${report.system.osFullName ?? report.system.os ?? '—'}`);
  out.push(`- Kernel: ${report.system.kernelVersion ?? '—'}`);
  out.push(`- Lynis version: ${report.meta.lynisVersion ?? '—'}`);
  out.push('');

  if (enriched) {
    out.push('---');
    out.push(
      `_Generated by Lynsight with **${enriched.meta.providerName}** — ${enriched.meta.enrichedCount} findings + ${
        Object.values(enriched.narratives).filter(Boolean).length
      } narrative sections._`,
    );
  }

  return out.join('\n');
}

function pushNarrative(out: string[], title: string, content: string | undefined) {
  if (!content) return;
  out.push(`## ${title}`);
  out.push('');
  out.push(content.trim());
  out.push('');
}
